# config.py
# User-configurable settings for the MT5 scalping bot

CONFIG = {
    'SYMBOL': 'EURUSD',
    'MAX_SIMULTANEOUS_TRADES': 1000,
    'MIN_PROFIT_USD': 0.01,
    'TRADE_VOLUME': 0.01,
    'DAILY_PROFIT_TARGET': 5.0,
    'CHECK_INTERVAL_MS': 10,
    'SLIPPAGE': 5,
    'MAGIC_NUMBER': 123456,
    'ORDER_COMMENT': 'XOXO_HFT',
    'SPREAD_THRESHOLD': 3,
    'MIN_TICK_DISTANCE': 5,
    'TICK_VELOCITY_WINDOW': 3,
    'TICK_VOLUME_THRESHOLD': 10,
}
